### PR TITLE
Create `Project.toml` file, delete `REQUIRE` file, fix AppVeyor

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Bump @mpastell Can you merge this?

**Comment by DilumAluthge** [comment]
Bump @mpastell

**Comment by DilumAluthge** [comment]
@mpastell Could you merge this pull request please?

**Comment by DilumAluthge** [comment]
Bump @mpastell

**Comment by mpastell** [comment]
Merged, thanks for the fix and sorry for the delay!

**Pull request merged**
