### PR TITLE
Multithreading via OpenMP

### PR DESCRIPTION
**Pull request by frodofine**
Adding OpenMP support to svm.cpp. Enabling it is a bit clunky, but standard for OpenMP support.

A potential issue is a compatible compiler for OpenMP is required to build the library. 

See:
[https://www.csie.ntu.edu.tw/~cjlin/libsvm/faq.html#f432](https://www.csie.ntu.edu.tw/~cjlin/libsvm/faq.html#f432)

### CODE REVIEW

**Comment by mpastell** [comment]
It seems that setting `OMP_NUM_THREADS` has no effect at runtime. This patch uses all cores regardless of what value I set. See also: https://software.intel.com/en-us/mkl-linux-developer-guide-changing-the-number-of-openmp-threads-at-run-time. 

It would be great if you could implement this in a way that you can change the number of threads at runtime.

**Comment by frodofine** [comment]
I believe that is compiler specific (GCC allowed me to set it through a runtime variable at least) and Intel's compiler is probably different. I tested this on a cluster, so they might be setting other variables behind the scenes as well.

That should be easy enough, but libgomp is specific to GCC so that solution is GCC specific.  So maybe one can change the API to accept the library name as well for people who compiled with a different compiler?

No I haven't, but I plan to later this week.

**Comment by mpastell** [comment]
On Ubuntu with GCC the environment variable only has an effect if its set before LIBSVM is loaded so it would be nicer to be able to set it using the C api. 

One option would be to add `set_num_threads` function to compiled libsvm library and call that from Julia, then it should work with whichever compiler is used.

**Comment by abhijithch** [comment]
Bump

**Comment by frodofine** [comment]
Bump

**Comment by mpastell** [comment]
Sorry for the delay and many thanks for this work. I mean to test this on Windows, but didn't have time and forgot! I'm merging this now. Many thanks for adding the Windows dll as well!

**Pull request merged**
