### PR TITLE
pre-built libsvm binaries using BinaryBuilder

### LINKED ISSUE #52: Cannot install LIBSVM
```
(@v1.4) pkg> add LIBSVM RDatasets
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
  Installed XML2_jll ──────── v2.9.9+4
  Installed Libiconv_jll ──── v1.16.0+2
  Installed Mocking ───────── v0.7.1
  Installed ScikitLearnBase ─ v0.5.0
  Installed LIBSVM ────────── v0.4.0
  Installed RData ─────────── v0.7.1
  Installed TimeZones ─────── v1.2.0
  Installed LIBLINEAR ─────── v0.5.1
  Installed RDatasets ─────── v0.6.8
   Updating `~/.julia/environments/v1.4/Project.toml`
  [b1bec4e5] + LIBSVM v0.4.0
  [ce6b1742] + RDatasets v0.6.8
   Updating `~/.julia/environments/v1.4/Manifest.toml`
  [8f5d6c58] + EzXML v1.1.0
  [2d691ee1] + LIBLINEAR v0.5.1
  [b1bec4e5] + LIBSVM v0.4.0
  [94ce4f54] + Libiconv_jll v1.16.0+2
  [78c3b35d] + Mocking v0.7.1
  [df47a6cb] + RData v0.7.1
  [ce6b1742] + RDatasets v0.6.8
  [6e75b9c4] + ScikitLearnBase v0.5.0
  [f269a46b] + TimeZones v1.2.0
  [02c8fc9c] + XML2_jll v2.9.9+4
   Building LIBLINEAR → `~/.julia/packages/LIBLINEAR/yTdp5/deps/build.log`
┌ Error: Error building `LIBLINEAR`: 
│ rm -f *~ zz.o
│ g++ -Wall -Wconversion -O3 -fPIC -c -o zz.o zz.cpp
│ make: g++: Command not found
│ Makefile:16: recipe for target 'zz.o' failed
│ make: *** [zz.o] Error 127
│ ERROR: LoadError: failed process: Process(`make lib`, ProcessExited(2)) [2]
│ 
│ Stacktrace:
│  [1] pipeline_error at ./process.jl:525 [inlined]
│  [2] run(::Cmd; wait::Bool) at ./process.jl:440
│  [3] run(::Cmd) at ./process.jl:438
│  [4] top-level scope at /home/cossio/.julia/packages/LIBLINEAR/yTdp5/deps/build.jl:4
│  [5] include(::String) at ./client.jl:439
│  [6] top-level scope at none:5
│ in expression starting at /home/cossio/.julia/packages/LIBLINEAR/yTdp5/deps/build.jl:1
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Operations.jl:899
   Building LIBSVM ───→ `~/.julia/packages/LIBSVM/5Z99T/deps/build.log`
┌ Error: Error building `LIBSVM`: 
│ make lib_normal || make lib_fallback
│ make[1]: Entering directory '/home/cossio/.julia/packages/LIBSVM/5Z99T/deps/libsvm-3.22'
│ make svm.o_normal || make svm.o_fallback
│ make[2]: Entering directory '/home/cossio/.julia/packages/LIBSVM/5Z99T/deps/libsvm-3.22'
│ g++ -Wall -Wconversion -O3 -fPIC -DENABLEOPENMP -fopenmp -c svm.cpp
│ make[2]: g++: Command not found
│ Makefile:41: recipe for target 'svm.o_normal' failed
│ make[2]: *** [svm.o_normal] Error 127
│ make[2]: Leaving directory '/home/cossio/.julia/packages/LIBSVM/5Z99T/deps/libsvm-3.22'
│ make[2]: Entering directory '/home/cossio/.julia/packages/LIBSVM/5Z99T/deps/libsvm-3.22'
│ g++  -c svm.cpp
│ make[2]: g++: Command not found
│ Makefile:44: recipe for target 'svm.o_fallback' failed
│ make[2]: *** [svm.o_fallback] Error 127
│ make[2]: Leaving directory '/home/cossio/.julia/packages/LIBSVM/5Z99T/deps/libsvm-3.22'
│ Makefile:38: recipe for target 'svm.o' failed
│ make[1]: *** [svm.o] Error 2
│ make[1]: Leaving directory '/home/cossio/.julia/packages/LIBSVM/5Z99T/deps/libsvm-3.22'
│ make[1]: Entering directory '/home/cossio/.julia/packages/LIBSVM/5Z99T/deps/libsvm-3.22'
│ make svm.o_normal || make svm.o_fallback
│ make[2]: Entering directory '/home/cossio/.julia/packages/LIBSVM/5Z99T/deps/libsvm-3.22'
│ g++ -Wall -Wconversion -O3 -fPIC -DENABLEOPENMP -fopenmp -c svm.cpp
│ make[2]: g++: Command not found
│ Makefile:41: recipe for target 'svm.o_normal' failed
│ make[2]: *** [svm.o_normal] Error 127
│ make[2]: Leaving directory '/home/cossio/.julia/packages/LIBSVM/5Z99T/deps/libsvm-3.22'
│ make[2]: Entering directory '/home/cossio/.julia/packages/LIBSVM/5Z99T/deps/libsvm-3.22'
│ g++  -c svm.cpp
│ make[2]: g++: Command not found
│ Makefile:44: recipe for target 'svm.o_fallback' failed
│ make[2]: *** [svm.o_fallback] Error 127
│ make[2]: Leaving directory '/home/cossio/.julia/packages/LIBSVM/5Z99T/deps/libsvm-3.22'
│ Makefile:38: recipe for target 'svm.o' failed
│ make[1]: *** [svm.o] Error 2
│ make[1]: Leaving directory '/home/cossio/.julia/packages/LIBSVM/5Z99T/deps/libsvm-3.22'
│ Makefile:10: recipe for target 'lib' failed
│ make: *** [lib] Error 2
│ ERROR: LoadError: failed process: Process(`make lib`, ProcessExited(2)) [2]
│ 
│ Stacktrace:
│  [1] pipeline_error at ./process.jl:525 [inlined]
│  [2] run(::Cmd; wait::Bool) at ./process.jl:440
│  [3] run(::Cmd) at ./process.jl:438
│  [4] top-level scope at /home/cossio/.julia/packages/LIBSVM/5Z99T/deps/build.jl:12
│  [5] include(::String) at ./client.jl:439
│  [6] top-level scope at none:5
│ in expression starting at /home/cossio/.julia/packages/LIBSVM/5Z99T/deps/build.jl:2
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Operations.jl:899
   Building TimeZones → `~/.julia/packages/TimeZones/OjMoF/deps/build.log`

(@v1.4) pkg> 
```

### PR DESCRIPTION
**Pull request by aviks**
The build scripts are [here](https://github.com/JuliaPackaging/Yggdrasil/tree/master/L/libsvm). The build uses the [released sources](https://github.com/cjlin1/libsvm/releases), and patches them for openmp use. 

There is a corresponding [PR to LIBLINEAR.jl](https://github.com/innerlee/LIBLINEAR.jl/pull/24)

Fix #52

### CODE REVIEW

**Comment by aviks** [comment]
@mpastell this should be ready to merge. Let me know if you have concerns. Would be good to get this tagged, since there are multiple reports of build issues.

**Comment by cossio** [comment]
Yes, please get this merged soon and tag a new release. Cannot use the package because of this issue.

**Comment by laborg** [comment]
@mpastell It would be great if you could merge this PR!

**Comment by aviks** [comment]
I believe Matti is on vacation now, I'll ping him again once he's scheduled to be back.

**Comment by mpastell** [comment]
Thanks @aviks, merged and sorry for the delay!

**Pull request merged**
